{
  pkgs ? import ./pkgs.nix,
}: with pkgs;

let
  name = "dapp2nix";
  version = "0.0.0";
  gen-header = "# This file has been generated by ${name} ${version}, do not edit.";
in stdenv.mkDerivation {
  name = "${name}-${version}";
  src = lib.cleanSource ./.;

  buildInputs = [ makeWrapper ];

  phases = [ "unpackPhase" "installPhase" "fixupPhase" ];

  installPhase = ''
    mkdir -p $out/bin
    cp dapp2nix $out/bin
    wrapProgram $out/bin/dapp2nix \
      --set TEMPLATE_HEADER "${gen-header}" \
      --set PATH ${lib.makeBinPath [ coreutils gnused git ]}
  '';

  meta = with stdenv.lib; {
    description = "Generate a nix expressions for dapptool repos";
    homepage = "https://github.com/icetan/dapp2nix";
    license = licenses.unlicense;
    maintainers = [ { email = "me@icetan.org"; github = "icetan"; name = "Christopher Fredén"; } ];
  };
}
